name: build

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub on push event
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker.io/1013510225/115:dev

      - name: Release and push to Docker Hub on workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker.io/1013510225/115:latest
